# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: echo MSBuild
        run: msbuild -version
        
#       - name: Build Solution
#         run: msbuild .\src\AtHomesoft.sln -property:Configuration=Release -property:Platform=x86 -property:Architecture=x86
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

#   deploy:
# #   See process documented here to publish a ClickOnce deployment to GitHub Pages
# #   https://www.jeeshenlee.com/2020/10/how-to-host-clickonce-installer-on.html
#     runs-on: windows-latest
    
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
      
#       - name: setup-msbuild
#         uses: microsoft/setup-msbuild@v1
        
# #       - name: Deploy ClickOnce to GitHub Pages site
# #         run: msbuild publish ??
